# Opciones de la JVM para Gradle.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX obligatorio para librerías modernas (Material, WebKit, etc.).
android.useAndroidX=true

# Kotlin en modo oficial.
kotlin.code.style=official

# No generar clases R por cada librería (build más rápido).
android.nonTransitiveRClass=true
